# -*- coding: utf-8 -*-
"""email_slicer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHm-JADM6hh-cN98EXd1K9WANy-SUH0x

Email Slicer
"""

def email_slicer(email):
    if "@" not in email:
        return "❌ Invalid email address!"

    username, domain = email.split("@")
    return f"✅ Email Sliced!\nUsername: {username}\nDomain: {domain}"

user_email = input("Enter your email address: ")
print(email_slicer(user_email))