# -*- coding: utf-8 -*-
"""password_generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10o4q06IJps8GcuTCdTRHpFTRhqTW9WFn

Password Generator
"""

import random
import string

def generate_password(length=12):
    if length < 4:
        return "❌ Password length must be at least 4 characters."

    characters = string.ascii_letters + string.digits + string.punctuation

    password = ''.join(random.choice(characters) for _ in range(length))
    return password


try:
    length = int(input("Enter desired password length: "))
    print("🔐 Your Generated Password is:", generate_password(length))
except ValueError:
    print("❌ Please enter a valid number!")